spring:
  datasource:
    url: jdbc:mysql://carbon-nono.cdspom5j0apx.ap-northeast-2.rds.amazonaws.com:3306/CARBON_NONO?characterEncoding=utf8
    username: admin
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: hello.hellospring
  mapper-locations: mybatis/mapper/**/*.xml